services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    mem_limit: 2g
    memswap_limit: 2g

  fluentd:
    build: ./fluent/
    container_name: fluentd
    volumes:
      - ./fluent/fluent.conf:/fluentd/etc/fluent.conf
    depends_on:
      - elasticsearch

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
      - MINIO_AUDIT_WEBHOOK_ENABLE_efk=on
      - MINIO_AUDIT_WEBHOOK_ENDPOINT_efk=http://fluentd:9880/minio.audit
    command: server /data --console-address ":9001"

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - elasticsearch
  shorten-proxy:
    build: ./shorten-proxy/
    container_name: shorten
    ports:
      - "9003:9000"
    command: npm run start
    environment:
      # Change to a public domain name or IP address
      - BASE_URL=http://localhost:9003
    depends_on:
      - minio
  url-gen:
    build: ./url-generator/
    container_name: urlgen
    ports:
      - "9002:9002"
    command: python3 app.py
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin123
    depends_on:
      - shorten-proxy
volumes:
  es_data:
  grafana_data:
  minio_data:
