apiVersion: 1
datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    uid: "lab447es"
    jsonData:
      esVersion: 7.10
      timeField: "@timestamp"
